Added scr function.

diff --git a/.zshrc.d/func b/.zshrc.d/func
--- a/.zshrc.d/func
+++ b/.zshrc.d/func
@@ -140,6 +140,15 @@ lsdbus() {
               org.freedesktop.DBus.ListNames
 }
 
+# List osu! songs
+lsosu() {
+    if [[ $# -eq 0 ]]; then
+        ls /opt/osu/game/Songs
+    else
+        ls /opt/osu/game/Songs | grep -i "$1"
+    fi
+}
+
 # Print your most used shell commands
 mostused() {
     history \
@@ -175,24 +184,41 @@ rmln() {
 # Generate a dice roll
 roll() {
     local upper=$1
-    [ -z "$upper" ] && upper=100
+    [[ -z "$upper" ]] && upper=100
     echo $[ 1 + $[ RANDOM % ${upper} ]]
+}
+
+# Run one of my scripts without specifying the path
+scr() {
+    if [[ $1 != *.* ]]; then
+        local script="/usr/local/scripts/$1.sh"
+    else
+        local script="/usr/local/scripts/$1"
+    fi
+
+    if [[ ! -f "$script" ]]; then
+        printf >&2 'Cannot find script: "%s"\n' "$1"
+        return 1
+    fi
+
+    shift
+    $script $@
 }
 
 # Set the title of the terminal
 settitle() {
-   echo -ne "\e]2;$@\a\e]1;$@\a"; 
+   echo -ne "\e]2;$@\a\e]1;$@\a"
 }
 
-# Changes up how the train looks
+# Changes up how the sl train looks
 sl() {
     local sett=e
-    local rand=$[ RANDOM % 8 ]
+    local rand=$RANDOM
 
-    [ $[ $rand & 1 ] -gt 0 ] && sett+=a
-    [ $[ $rand & 2 ] -gt 0 ] && sett+=l
-    [ $[ $rand & 4 ] -gt 0 ] && sett+=F
-    [ $[ $rand & 8 ] -gt 0 ] && sett+=c
+    [[ $[ $rand & 1 ] -gt 0 ]] && sett+=a
+    [[ $[ $rand & 2 ] -gt 0 ]] && sett+=l
+    [[ $[ $rand & 4 ] -gt 0 ]] && sett+=F
+    [[ $[ $rand & 8 ] -gt 0 ]] && sett+=c
     
     env sl -$sett
 }
@@ -213,7 +239,7 @@ suspendnow() {
 suspendlock() {
     confirm && {
         suspendnow
-        ~/Scripts/wm/i3_lock.sh
+        scr wm/i3_lock.sh
     }
 }
 
